### ISSUE TITLE
VPLEX UTC Time Zone

### ISSUE THREAD

**Issue by eschek87** [vzaigrin/UniversalStorageCollector#2]
Hi,

is there a way to change the time zone in the data that comes from vplex? I tried to change the time zone in the graphite conf file, but it ignores the setting. I need to have the times in utc+1. Vplex is configured touse our ntp servers. If i opened the vplex performance monitor webfrontend it shows the data in our local time. Do you have an idea?

Regards,
Stephan

**Comment by vzaigrin** [comment]
You could setup Timezone in the dashboard setting in Grafana.

**Comment by eschek87** [comment]
Do you mean this setting? It is already set to local browser time. But this did not change anything
![2017-02-03 14_09_34-grafana - vplex](https://cloud.githubusercontent.com/assets/22763868/22592564/a2864f0e-ea1a-11e6-9cb6-56d67ba94f71.jpg)

**Comment by vzaigrin** [comment]
Yes, if you set this value not to local browser time it should show correct time.
I use this setting for my VPLEX and it works.
![vplex](https://cloud.githubusercontent.com/assets/7489028/22593033/b9743e70-ea2d-11e6-8f15-4c9bceac794c.png)
![vplex2](https://cloud.githubusercontent.com/assets/7489028/22593054/d789f4b8-ea2d-11e6-958d-2d46c4a20461.png)

**Comment by eschek87** [comment]
Weird...if i set to UTC it goes one our back. Now it is 14:32. With local browser time it show the last value one hour back. Wit UTC it goes 2 hours back.
![2017-02-03 14_32_02-grafana - vplex](https://cloud.githubusercontent.com/assets/22763868/22593205/c1fc1c26-ea1d-11e6-90b5-4b5b8dd3f680.png)

**Comment by vzaigrin** [comment]
VPLEX displays date in UTC.
Compare output of _date_ command and last value in monitor file.
![vplex3](https://cloud.githubusercontent.com/assets/7489028/22595018/ba4ff02e-ea36-11e6-953f-5abc2f6f934f.png)

**Comment by eschek87** [comment]
Yes sure. Both have UTC. That's why i ask if there is a way to add an hour...i thought this is possible with the graphite conf file local_settings.py but this changes nothing. Seems to ignore my setting. Maybe i will ask this on graphite site on github.


Gesendet von unterwegs

Von: Vadim Zaigrin <notifications@github.com<mailto:notifications@github.com>>
Datum Freitag, 03. Feb. 2017, 15:32
An: vzaigrin/UniversalStorageCollector <UniversalStorageCollector@noreply.github.com<mailto:UniversalStorageCollector@noreply.github.com>>
Cc: Liebner, Stephan <Stephan.Liebner@medizin.uni-leipzig.de<mailto:Stephan.Liebner@medizin.uni-leipzig.de>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [vzaigrin/UniversalStorageCollector] VPLEX UTC Time Zone (#2)


VPLEX displays date in UTC.
Compare output of date command and last value in monitor file.
[vplex3]<https://cloud.githubusercontent.com/assets/7489028/22595018/ba4ff02e-ea36-11e6-953f-5abc2f6f934f.png>

**Comment by eschek87** [comment]
I have now set in local_settings.py and the system time of my ubuntu on utc. If i now use local browser time in grafana i got the right timestamps. Thanks for your help
