### ISSUE TITLE
typo in sample collector.xml

### ISSUE THREAD

**Issue by starryfields** [vzaigrin/UniversalStorageCollector#5]
In the sample config, the following method is missing the objectType definition.

        <method name="fastcache">
          <type>simple</type>
          <cmd>cache -fast -info</cmd>
          <paramList>
            <param>Percentage Dirty SPA</param>
            <param>MBs Flushed SPA</param>
            <param>Percentage Dirty SPB</param>
            <param>MBs Flushed SPB</param>
          </paramList>
        </method>

The collector errors like such.

Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: [ERROR] [02/23/2017 11:08:50.203] [USC-akka.actor.default-dispatcher-4] [akka://USC/user/VNX01L.block] ke
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: java.util.NoSuchElementException: key not found: objectType
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at scala.collection.MapLike$class.default(MapLike.scala:228)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at scala.collection.AbstractMap.default(Map.scala:59)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at scala.collection.MapLike$class.apply(MapLike.scala:141)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at scala.collection.AbstractMap.apply(Map.scala:59)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at universalstoragecollector.VNXBlock.simple(VNXBlock.scala:115)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at universalstoragecollector.VNXBlock$$anonfun$ask$1.apply(VNXBlock.scala:101)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at universalstoragecollector.VNXBlock$$anonfun$ask$1.apply(VNXBlock.scala:87)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at scala.collection.immutable.List.foreach(List.scala:381)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at universalstoragecollector.VNXBlock.ask(VNXBlock.scala:87)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at universalstoragecollector.Storage$$anonfun$receive$1.applyOrElse(Storage.scala:10)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at universalstoragecollector.Storage.aroundReceive(Storage.scala:5)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at akka.actor.ActorCell.invoke(ActorCell.scala:495)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at akka.dispatch.Mailbox.run(Mailbox.scala:224)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Feb 23 11:08:50 systemsdata01.its.uidaho.edu java[15109]: at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by vzaigrin** [comment]
Yes, objectType for fastcache method was missing.
It should be fastcache.
I have updated this sample config.

**Comment by starryfields** [comment]
Thanks!
