### ISSUE TITLE
VNX1 CPU Utilization

### ISSUE THREAD

**Issue by eschek87** [vzaigrin/UniversalStorageCollector#6]
For a vnx1 system the cpu utilization (prct busy) reports always the same value. I have found a post that describes the calculation: https://community.emc.com/docs/DOC-16144

For percentage: 100 * (busy_ticks / (busy_ticks + idle_ticks))

Is it possible to include this?

**Comment by vzaigrin** [comment]
This is agains a concept of this tool: extract data by executing commands.
I could advise to add 'Prct Idle' parameter and make calculations in Graphite.

**Comment by eschek87** [comment]
Prct Idle is the same problem. I will add Controller busy ticks, Controller idle ticks as <param> and do calculation with grafana/graphite
